//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICResponse.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LoginPassword {
            get {
                return ((string)(this["LoginPassword"]));
            }
            set {
                this["LoginPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LoginUsername {
            get {
                return ((string)(this["LoginUsername"]));
            }
            set {
                this["LoginUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AgentID {
            get {
                return ((int)(this["AgentID"]));
            }
            set {
                this["AgentID"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INSERT INTO agents (first, last, email, password) VALUES (?first, ?last, ?email, " +
            "?password)")]
        public string AgentInsert {
            get {
                return ((string)(this["AgentInsert"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM agents WHERE email=")]
        public string AgentSelectByEmail {
            get {
                return ((string)(this["AgentSelectByEmail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT MAX(uid) FROM calls WHERE tech=")]
        public string CallCurrentIDSelect {
            get {
                return ((string)(this["CallCurrentIDSelect"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT NOW()")]
        public string GetDBTime {
            get {
                return ((string)(this["GetDBTime"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT tech,AVG(TIME_TO_SEC(TIMEDIFF(stopTime,startTime))) AS TechAverageDuration" +
            ",COUNT(*) AS NumOfRows FROM calls WHERE date=CURDATE() GROUP BY tech")]
        public string GetGroupedCalls {
            get {
                return ((string)(this["GetGroupedCalls"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("logout")]
        public string LoginLevel {
            get {
                return ((string)(this["LoginLevel"]));
            }
            set {
                this["LoginLevel"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DELETE FROM calls WHERE ticketID=")]
        public string DeleteCurrentCall {
            get {
                return ((string)(this["DeleteCurrentCall"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.163")]
        public string DBServer {
            get {
                return ((string)(this["DBServer"]));
            }
            set {
                this["DBServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("icresponse")]
        public string DBName {
            get {
                return ((string)(this["DBName"]));
            }
            set {
                this["DBName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("remoter")]
        public string DBUser {
            get {
                return ((string)(this["DBUser"]));
            }
            set {
                this["DBUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A9m1n")]
        public string DBPass {
            get {
                return ((string)(this["DBPass"]));
            }
            set {
                this["DBPass"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT color FROM agents WHERE email=@email")]
        public string SelectColorForAgent {
            get {
                return ((string)(this["SelectColorForAgent"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LoginNick {
            get {
                return ((string)(this["LoginNick"]));
            }
            set {
                this["LoginNick"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT ticketID, tech, brand, company,contact,phone,email, date, startTime, stopT" +
            "ime, holdtime, duration, issue, resolution, iscase, casenumber, queuename FROM c" +
            "alls WHERE date=CURDATE() ORDER BY ticketID DESC")]
        public string TodayCallSelect {
            get {
                return ((string)(this["TodayCallSelect"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("large")]
        public string SelectedFontSize {
            get {
                return ((string)(this["SelectedFontSize"]));
            }
            set {
                this["SelectedFontSize"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT AVG(TIME_TO_SEC(TIMEDIFF(stopTime,startTime))) AS OverallAverageDuration F" +
            "ROM calls WHERE date=CURDATE() ")]
        public string GetOverallAverageTime {
            get {
                return ((string)(this["GetOverallAverageTime"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFE51400")]
        public global::System.Windows.Media.Color SelectedAccentColor {
            get {
                return ((global::System.Windows.Media.Color)(this["SelectedAccentColor"]));
            }
            set {
                this["SelectedAccentColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pack://application:,,,/ICResponse;component/Assets/ModernUI.ICRTheme.xaml")]
        public global::System.Uri SelectedThemeSource {
            get {
                return ((global::System.Uri)(this["SelectedThemeSource"]));
            }
            set {
                this["SelectedThemeSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("icrealtime")]
        public string SelectedThemeDisplayName {
            get {
                return ((string)(this["SelectedThemeDisplayName"]));
            }
            set {
                this["SelectedThemeDisplayName"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT name,phone,status,passed  FROM acdoverview WHERE name !=\'John Bartel\' AND " +
            "name !=\'Michael Olivera\' AND name !=\'Brian Roberts\' AND name !=\'Jason Zandman\' A" +
            "ND name NOT LIKE \'ICR%\'")]
        public string GetOverview {
            get {
                return ((string)(this["GetOverview"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT COUNT(*) FROM acdoverview WHERE phone=\'Idle\'  AND name !=\'John Bartel\' AND" +
            " name !=\'Michael Olivera\' AND name !=\'Brian Roberts\' AND name !=\'Jason Zandman\' " +
            "AND name NOT LIKE \'ICR%\'")]
        public string GetIdleCallCounts {
            get {
                return ((string)(this["GetIdleCallCounts"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT COUNT(*) FROM acdoverview WHERE phone=\'In Call\'  AND name !=\'John Bartel\' " +
            "AND name !=\'Michael Olivera\' AND name !=\'Brian Roberts\' AND name !=\'Jason Zandma" +
            "n\' AND name NOT LIKE \'ICR%\'")]
        public string GetInCallCounts {
            get {
                return ((string)(this["GetInCallCounts"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT COUNT(*) FROM calls WHERE date=CURDATE()")]
        public string GetTotalDailyCallCount {
            get {
                return ((string)(this["GetTotalDailyCallCount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public int smtpport {
            get {
                return ((int)(this["smtpport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")]
        public string smtphost {
            get {
                return ((string)(this["smtphost"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("icresponse.pwreset@gmail.com")]
        public string smtpusername {
            get {
                return ((string)(this["smtpusername"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Samurai8")]
        public string smtppassword {
            get {
                return ((string)(this["smtppassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ICResponse Password Request")]
        public string smtpsubjectline {
            get {
                return ((string)(this["smtpsubjectline"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("You have requested your current password:")]
        public string smtpmessagebody {
            get {
                return ((string)(this["smtpmessagebody"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ICResponse Password Request.")]
        public string Emailmessageheader {
            get {
                return ((string)(this["Emailmessageheader"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM agents WHERE email=@email")]
        public string SelectAgentByEmail {
            get {
                return ((string)(this["SelectAgentByEmail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT ticketID, tech, brand, company,contact,phone,email, date, startTime, stopT" +
            "ime, holdtime, duration, issue, resolution, iscase, casenumber, queuename FROM c" +
            "alls ORDER BY ticketID DESC LIMIT 100")]
        public string GetAllCalls {
            get {
                return ((string)(this["GetAllCalls"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM voicemails")]
        public string GetVoicemails {
            get {
                return ((string)(this["GetVoicemails"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT startTime,COUNT(*) FROM calls WHERE date=CURDATE() GROUP BY startTime")]
        public string GetCallVolume {
            get {
                return ((string)(this["GetCallVolume"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgentFirstName {
            get {
                return ((string)(this["AgentFirstName"]));
            }
            set {
                this["AgentFirstName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AgentLastName {
            get {
                return ((string)(this["AgentLastName"]));
            }
            set {
                this["AgentLastName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"INSERT INTO calls (tech, status, company, contact, phone, email, date, startTime, stopTime, holdtime, duration, brand, issue, resolution, iscase, casenumber) VALUES (?tech, ?status, ?company, ?contact, ?phone, ?email, ?date, ?startTime, ?stopTime, ?holdtime, ?duration, ?brand, ?issue, ?resolution, ?iscase, ?casenumber)")]
        public string InsertCallRecord {
            get {
                return ((string)(this["InsertCallRecord"]));
            }
            set {
                this["InsertCallRecord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UPDATE calls SET company=?company, contact=?contact, phone=?phone, email=?email, " +
            "brand=?brand, issue=?issue, resolution=?resolution, iscase=?iscase, casenumber=?" +
            "casenumber WHERE uid=?uid ")]
        public string UpdateCallRecord {
            get {
                return ((string)(this["UpdateCallRecord"]));
            }
            set {
                this["UpdateCallRecord"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT name FROM acdoverview WHERE phone=\'In Call\'")]
        public string GetActiveCalls {
            get {
                return ((string)(this["GetActiveCalls"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://acd2.ststelecom.com/QueueManager/Login.php?")]
        public string ACDLoginURL {
            get {
                return ((string)(this["ACDLoginURL"]));
            }
            set {
                this["ACDLoginURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://acd2.ststelecom.com/QueueManager/ReadyBusy.php?")]
        public string ACDGoBusy {
            get {
                return ((string)(this["ACDGoBusy"]));
            }
            set {
                this["ACDGoBusy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://acd2.ststelecom.com/QueueManager/activity_monitor.php")]
        public string ACDOverViewURL {
            get {
                return ((string)(this["ACDOverViewURL"]));
            }
            set {
                this["ACDOverViewURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT ticketID FROM calls WHERE uid=")]
        public string getTicketIDFromUID {
            get {
                return ((string)(this["getTicketIDFromUID"]));
            }
            set {
                this["getTicketIDFromUID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT MAX(ticketID) FROM calls WHERE tech=")]
        public string getMaxTicketForTech {
            get {
                return ((string)(this["getMaxTicketForTech"]));
            }
            set {
                this["getMaxTicketForTech"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT company FROM calls WHERE uid=")]
        public string getCompanyFromUID {
            get {
                return ((string)(this["getCompanyFromUID"]));
            }
            set {
                this["getCompanyFromUID"] = value;
            }
        }
    }
}
